### ISSUE TITLE
Updating XSL and CSS

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/Missionary-Travels#7] opened 2017-03-16 01:12 UTC
Please resync. I've updated the CSS and XSL. These are not done yet, so no need to start checking them. Rather, could you:

1) Clean up our MT Github folder and get rid of everything that's not necessary or at least move it into a subfolder called "done" or something like that?

2) Please put up a few real (not test) MT files. I need to test a few things and would like to work with what you'll actually be using.

**Comment by justindlivingstone** [comment] 2017-03-16 10:07
Thanks Adrian. I've cleaned up the folder, getting rid of everything aside from a file (liv_015006) that looks like one of yours. I can't remember why we put it there so decided to leave it for you.

I've put 6 of my MT files into the github folder. As well as four files in DL's hand, the last two (from 000101) are in different hands: that of Charles and #U5. Together, they cover everything.

Thanks again for your help with this.

**Comment by awisnicki** [comment] 2017-03-16 11:27
OK, thanks! But I think you forgot to commit and sync your changes as I'm not seeing anything new when I resync.

**Comment by justindlivingstone** [comment] 2017-03-16 11:30
Hmm...I'd definitely committed the changes but might not have hit sync.
I've just done so, so hopefully you'll have the files now.

**Comment by awisnicki** [comment] 2017-03-16 13:02
Yes, it worked this time!

**Comment by awisnicki** [comment] 2017-03-19 00:12
OK, resync. It's over to you for review. I think this is looking good. A couple of notes:

1) You'll notice that the header doesn't quite work right in relation to the text on liv_000101_0194_TEI. Just ignore that. It will work when we integrate all the files into longer ones.

2) I turned off the italics on Charles and U5 as it was messing up a bunch of stuff. Italics is not the way we'll go with differentiating anyway.

3) I don't like how far things are floating out in the left margin, but also don't see a way to fix this. I've brought in everything a touch, so it's slightly better but it'd be nice to see this improved even more. Any ideas? The only other thing I can think of (very minor) is reducing the font size of the things in the left margin to 90%.

**Comment by justindlivingstone** [comment] 2017-03-19 14:53
This is great. I'll review it more detail soon, but it looks good so far.

In answer to 2, I agree that turning off italics is the right move. I'll have a look at some other fonts and will run it by you.

As for 3, I agree the notes float a bit far to the left. I think one reason they need to be quite far over is because there are a few notes in which the lines are quite long, and they screw up the body of the text when they're too close. I'd certainly like them to appear closer in general, if possible. I like the idea of reducing the size to 90%.

**Comment by awisnicki** [comment] 2017-03-20 14:03
OK, great. Let me know. If all looks OK overall, then we should move to sorting out the various lesser issues, and you can make separate tickets for those. For #2, don't worry about that too much right now. That will be easy to sort out when we get to it. For #3, go ahead and make it font-size:.9em for the things floating in the margin & see if that looks OK with you. I marked most of the things in the CSS that need to be changed in this respect with /*Changed by AW*/ but you should see if I missed anything. Finally, note that the XSL has a handful of queries/action items for you.

**Comment by justindlivingstone** [comment] 2017-03-23 16:39
A small issue with this one. I've made font-size .9m for things floating in the margin (i.e. `note.marginleft).` The problem is that this also makes every piece of text added in the margin appear .9 as well (i.e. any text that has `add.marginleft`). This means that words appearing in the body of the text in square brackets - signalling they're from the margin - are also being reduced in size.

I've tried putting 1em on `add.marginleft` and .9 on `note.marginleft` but it seems to choose one or the other. I suspect this is because all my notes in the marginleft are also within an `add` tag...

This might not be a problem. Maybe it looks good to have text added from the margin appearing in a smaller font. It might be another way, in addition to square brackets, to signal the text is from another part of the page. What do you think?

Any of the files in github will give examples of this issue.

**Comment by awisnicki** [comment] 2017-03-23 17:43
And I think I've resolved this. Please resync and check. If it looks correct, then the next step is to take the things in the left margin and bring them in. For that I'll need some examples where there's a lot of/maximum text in the left margin so I can test just how much max the text can be brought in.

**Comment by justindlivingstone** [comment] 2017-03-23 18:15
Ah, I see what you did. I should have thought of that! I'll find you the longest marginal note that I can, so we can work on this. Thanks!

**Comment by awisnicki** [comment] 2017-04-25 01:48
Is this resolved?

**Comment by justindlivingstone** [comment] 2017-04-25 09:00
Yes, it's resolved. I've brought the notes in as far as they can go. We still need to settle on the font for Charles, but that's really a separate issue.

**Closed as completed by justindlivingstone** 2017-04-25 09:00 UTC
